openapi: 3.0.0
info:
  title: Registration
  description: entertainment-web-app API
  version: 0.1.9

servers:
  - url: https://multi-step-api-da0808a28bdb.herokuapp.com/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /movies:
    get:
      tags:
        - Movies
      responses:
        "200":
          description: get all movies info successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /login:
    get:
      tages:
        - Logs
      responses:
        "200":
          description: get login password
          content:
            application/json:
              schema:
                type: arry
              items:
                type: string
