openapi: 3.0.0
info:
  title: Registration
  description: entertainment-web-app API
  version: 0.1.9

servers:
  - url: https://entertainment-web-app-api-production-18e2.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /movies:
    get:
      tags:
        - Movies
      security:
        - bearerAuth: []
      responses:
        "200":
          description: get all movies info successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /login:
    post:
      tags:
        - SignUp
      requestBody:
        description: create user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                id:
                  type: string
            example:
              name: nikita
              password: nikita
      responses:
        "200":
          description: user is loged
  /signup:
    post:
      tags:
        - SignUp
      requestBody:
        description: create user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                id:
                  type: string
            example:
              name: nikita
              password: nikita
      responses:
        "200":
          description: user is created
